export enum LENGTH_CONSTANTS {
    PASSWORD_MIN = 8,
    PASSWORD_MAX = 16,
}

export enum OUR_MISSION_VISION_SECTION {
    SHORT_DESCRIPTION = "",
    OUR_MISSION_DESCRIPTION = "",
    OUR_VISION_DESCRIPTION = "",

}

export enum WHY_CHOOSE_US_SECTION {
    SHORT_DESCRIPTION = "",
    EXPERT_GUIDANCE_DESCRIPTION = "",
    CLIENT_CENTRIC_DESCRIPTION = "",

}